# Generated by Django 5.2.5 on 2026-08-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0002_patient_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_tests', to='patients.patient'),
        ),
    ]
