# Generated by Django 5.2.5 on 2026-08-17 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('nurse_number', models.CharField(max_length=15, unique=True)),
                ('qualification', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='nurse_profile_pic')),
                ('nurse_bed_no', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurses', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
