# Generated by Django 5.2.5 on 2026-08-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0002_patient_room'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('SCHEDULED', 'Scheduled'), ('REFERRAL', 'Referral')], default='SCHEDULED', max_length=20)),
                ('reason', models.TextField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], default='ADMITTED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='departments.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='patients.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='rooms.room')),
            ],
        ),
    ]
